### ISSUE TITLE
沙箱模式下  回调接口

### ISSUE THREAD

**Issue by chenjiabin** [zoujingli/pay-php-sdk#1]
$pay->driver('wechat')->gateway('mp')->verify(file_get_contents('php://input'));

sign 验证不通过,
正式环境是可以的

sandbox_signkey 沙箱密钥
wechat.php 171 return $this->getSign($data) === $sign ? $data : false;

**Comment by chenjiabin** [comment]
mch_key 是固定的。获取一次。 写死到配置文件中就行。 不需要每次获取 sandbox_signkey 沙箱密钥

**Comment by zoujingli** [comment]
Thanks
