### ISSUE TITLE
微信支付回调不停止一直回调，因为echo 'success'不是正确格式，微信需要的是xml

### ISSUE THREAD

**Issue by wonerlox** [zoujingli/pay-php-sdk#14]
// 下面是项目的真实代码
/*
$pay = new Pay\Pay($config);
$notifyInfo = $pay->driver('wechat')->gateway('mp')->verify(file_get_contents('php://input'));
// 支付通知数据获取成功
if ($notifyInfo['result_code'] == 'SUCCESS' && $notifyInfo['return_code'] == 'SUCCESS') {
    $order_no = substr($notifyInfo['out_trade_no'], 0, 10);
    // 更新订单状态
    $this->updateOrder($order_no, $notifyInfo['transaction_id'], $notifyInfo['cash_fee'] / 100, 'wechat');
}
echo 'success';
*/

此处微信需要的正确返回格式是
<xml>
  <return_code><![CDATA[SUCCESS]]></return_code>
  <return_msg><![CDATA[OK]]></return_msg>
</xml>
直接 echo 'success'; 微信不识别，仍然不停的通知服务器。
而你这里写的是  “项目真实代码”，容易给人产生误导。
毕竟使用者选择相信你。哈哈哈

**Comment by zoujingli** [comment]
![image](https://user-images.githubusercontent.com/4349951/61193175-5a5c4580-a6ec-11e9-8226-50c2c89cc3ec.png)
抱歉，这个项目已经很久没有维护了，目前主要开发精力已经转到 WechatDeveloper+ThinkAdmin。
针对你所遇到这个问题，之前微信商户是支持，后面微信商户接口标准化之后才不支持。
文档我会进行修改一下，由于文档给你带来的不便还请谅解！
