### ISSUE TITLE
求问可不可以有个代码结构说明？

### ISSUE THREAD

**Issue by niaiwomattt** [zoujingli/pay-php-sdk#7]
比如哪个目录式干嘛的？调用结构，根据文件结构，还是代码之间的结构说明，方便别人扩展啊，我大致看懂了，但是还是有有点模糊。

**Comment by zoujingli** [comment]
嗯，建议参考下 WeChatDeveloper 重新开发一套，我也准备再搞一套
这个SDK的结构感觉有些复杂了
